### ISSUE TITLE
hue all STATE

### ISSUE THREAD

**Issue by andrei4002** [soffes/hue#36]
is the hue all STATE command working? for me it always gives a false result

hue all STATE
{"success"=>{"/lights/1/state/on"=>false}}
{"success"=>{"/lights/2/state/on"=>false}}
{"success"=>{"/lights/3/state/on"=>false}}

when i turn one light on for example it gives a response saying it's on, but after that, if i call state it will say it's off

(running hue bridge 2.0 with the latest firmware update available)

**Comment by christhomson** [comment]
I don't think you're supposed to be executing `hue all STATE` literally. Instead, you should be substituting `STATE` for either `on` or `off`: `hue all on` or `hue all off`.

The result you're seeing is due to [the code](https://github.com/soffes/hue/blob/6bd25f4be7864129e2bd00fa144ea01ba453dcad/lib/hue/cli.rb#L37) only checking for `on`, and assuming everything else should be interpreted as not being `on` - so `STATE` is interpreted as `off` essentially.
